words={
    "subject":["i","you","they","we","it","she","he"],
    "be_verb+subject":{
        "am":["i"],
        "are":["you","they","we"],
        "is":["it","she","he"]
    },
    "normal_verb":{
        "normal":[
            "run",
            "walk",
            "drove",
            "work",
            "study"
        ],
        "special":[
            ["like","place"],["like","sports"],
            ["love","place"],["love","sports"],
            #########
            ["can","sports"],
            ["do","sports"],
            ["good at","sports"],
            #########
            ["go","place"],["play","sports"],
        ]
    },
    "be_verb_use_noun":[
        "be","animal"
    ],
    "noun":{
        "be":[
            "tired","full","busy","hungly","hot","cold","cool","warm"
        ],
        "place":["home","school","hotel","station","bus terminal","market","shop","city"],
        "sports":["sucker","busketball","baseball","tennis","tabletennis"],
        "animal":["cat","dog","monkey","mouse"]
    },
    "be_verb":{
        "normal":[
            "am","are","is"
        ],
        "past":{
            "am":"was",
            "are":"were",
            "is":"was"
        }
    }
}